M48
; DRILL file {KiCad (6.0.6-69-g6d26e8e3e8)} date Wed Jul 20 16:26:29 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-20T16:26:29-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-69-g6d26e8e3e8)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
%
G90
G05
T1
X52.0Y-113.8
X352.2Y-113.2
T0
M30
